Feat/present section
KyzAlexander/DiplomProject pull request #3
Opened 2021-11-24 09:52 UTC by KyzAlexander

Есть элементы которые не становятся как надо. Там в коде комментами помечены. И адаптив на 1050 слетает, но это скорее всего из-за элементов, которые не становятся.

2021-11-24 14:06 UTC, aleksey-drozdov requested changes

2021-11-24 14:06 UTC, aleksey-drozdov commented on src/assets/styles/styles.scss
> +@import "src/assets/styles/sections/_presentSection.scss";
заменить путь к файлу аналогично с хедером

2021-11-24 14:06 UTC, aleksey-drozdov commented on src/assets/styles/util/_var.scss
> +$ColorTextOverTitle: #FF2625;
уже пять одинаковых переменных с крассным цветом. можно заменить на одну меременную с названием $ColorRed  и всё. 
касается и остальных переменных

2021-11-24 14:06 UTC, aleksey-drozdov commented on src/assets/styles/sections/_header.scss
> +  z-index: 5;
лучше убрать эти свойства, пусть хедер скролится вместе с остальным. а то не очень красиво выглядит когда он на другие элементы залазит. 

если успеем, то потом добавим js, что бы это красиво смотрелось

2021-11-24 14:06 UTC, aleksey-drozdov commented on src/assets/styles/sections/_presentSection.scss
> +    position: absolute;
т.к. у presentSection нет position:relative, то топ и лефт считаются от боди.

2021-11-24 14:06 UTC, aleksey-drozdov commented on src/components/presentSection.pug
> +section.presentSection.conteiner
conteiner ошибка в названии класса, из-за чего стили контейнера не работают

2021-11-24 14:06 UTC, aleksey-drozdov commented on src/assets/styles/sections/_presentSection.scss
> +    margin-left: 215px;
ненужный марджин. думаю после исправления названия контейнера его можно будет удалить

2021-11-24 14:06 UTC, aleksey-drozdov commented on src/assets/styles/sections/_presentSection.scss
> +    background: url("../images/presentSectionBacgroundPhoto.png") no-repeat;
путь к файлу должен быть /assets/images/......

2021-11-24 18:34 UTC, KyzAlexander commented on src/assets/styles/styles.scss
> +@import "src/assets/styles/sections/_presentSection.scss";
+

2021-11-24 18:34 UTC, KyzAlexander commented on src/assets/styles/util/_var.scss
> +$ColorTextOverTitle: #FF2625;
+

2021-11-24 18:39 UTC, KyzAlexander commented on src/assets/styles/sections/_header.scss
> +  z-index: 5;
да, согласен чтобы он скролился со всем остальным, а как тогда девушку засунуть под хедер?

2021-11-24 18:40 UTC, KyzAlexander commented on src/assets/styles/sections/_presentSection.scss
> +    position: absolute;
сделал presentSection свойство position:relative

2021-11-24 18:45 UTC, KyzAlexander commented on src/components/presentSection.pug
> +section.presentSection.conteiner
+

2021-11-24 18:47 UTC, KyzAlexander commented on src/assets/styles/sections/_presentSection.scss
> +    margin-left: 215px;
если эти марджены убрать, то блок с текстом съезжает

2021-11-24 18:49 UTC, KyzAlexander commented on src/assets/styles/sections/_presentSection.scss
> +    background: url("../images/presentSectionBacgroundPhoto.png") no-repeat;
+

2021-11-25 09:40 UTC, KyzAlexander commented on src/assets/styles/sections/_presentSection.scss
> +    background: url("../images/presentSectionBacgroundPhoto.png") no-repeat;
все никак не могу выровнять эту девушку, чтобы она и под хедер залезла и растянулась на всю ширину (

![image](https://user-images.githubusercontent.com/93609052/143417196-82130ccf-3b0d-4e5f-94b0-4c8d937147ba.png)

2021-11-25 09:49 UTC, aleksey-drozdov approved these changes

2021-11-25 11:54 UTC, merged