Feat/description section
KyzAlexander/DiplomProject pull request #9
Opened 2021-11-28 15:26 UTC by KyzAlexander

2021-11-29 14:56 UTC, aleksey-drozdov requested changes
на размерах 425 нет адаптива. ломается эта секция

2021-11-29 14:56 UTC, aleksey-drozdov commented on src/components/icon1.pug
> +svg(width='50' height='50' viewbox='0 0 50 50' fill='none' xmlns='http://www.w3.org/2000/svg')
создать папку для всех иконок и прочего подобного и перенести туда все эти файлы

2021-11-30 06:48 UTC, KyzAlexander commented on src/components/icon1.pug
> +svg(width='50' height='50' viewbox='0 0 50 50' fill='none' xmlns='http://www.w3.org/2000/svg')
создал папку и исправил адаптив на размерах 425

2021-11-30 08:10 UTC, aleksey-drozdov approved these changes

2021-11-30 08:38 UTC, merged